name: modelmerge
channels:
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aws-c-auth=0.7.31=hcdce11a_5
  - aws-c-cal=0.7.4=hd3f4568_4
  - aws-c-common=0.9.31=hb9d3cd8_0
  - aws-c-compression=0.2.19=hf20e7d7_4
  - aws-c-event-stream=0.4.3=h72d8268_7
  - aws-c-http=0.8.10=h6bb76cc_5
  - aws-c-io=0.14.20=h389d861_2
  - aws-c-mqtt=0.10.7=had056f2_5
  - aws-c-s3=0.7.0=hc85afc5_0
  - aws-c-sdkutils=0.1.19=hf20e7d7_6
  - aws-checksums=0.1.20=hf20e7d7_3
  - aws-crt-cpp=0.28.5=h8c310ae_4
  - aws-sdk-cpp=1.11.407=h8fdd00c_4
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - binutils_impl_linux-64=2.43=h4bf12b8_1
  - binutils_linux-64=2.43=h4852527_1
  - bokeh=3.6.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cffi=1.17.1=py311hf29c0ef_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - contourpy=1.3.0=py311hd18a35c_2
  - cuda-cccl_linux-64=12.6.77=0
  - cuda-crt-dev_linux-64=12.6.77=0
  - cuda-crt-tools=12.6.77=0
  - cuda-cudart=12.6.77=0
  - cuda-cudart-dev=12.6.77=0
  - cuda-cudart-dev_linux-64=12.6.77=0
  - cuda-cudart-static=12.6.77=0
  - cuda-cudart-static_linux-64=12.6.77=0
  - cuda-cudart_linux-64=12.6.77=0
  - cuda-driver-dev_linux-64=12.6.77=0
  - cuda-nvcc=12.6.77=0
  - cuda-nvcc-dev_linux-64=12.6.77=0
  - cuda-nvcc-impl=12.6.77=0
  - cuda-nvcc-tools=12.6.77=0
  - cuda-nvcc_linux-64=12.6.77=0
  - cuda-nvvm-dev_linux-64=12.6.77=0
  - cuda-nvvm-impl=12.6.77=0
  - cuda-nvvm-tools=12.6.77=0
  - cuda-version=12.6=h7480c83_3
  - cytoolz=1.0.0=py311h9ecbd09_1
  - dask=2024.9.0=pyhd8ed1ab_0
  - dask-core=2024.9.0=pyhd8ed1ab_0
  - dask-cuda=24.10.00=py311_241009_g4e45758_0
  - dask-expr=1.1.14=pyhd8ed1ab_0
  - dask-jobqueue=0.9.0=pyhd8ed1ab_0
  - distributed=2024.9.0=pyhd8ed1ab_0
  - emcee=3.1.6=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - gcc_impl_linux-64=12.4.0=hb2e57f8_1
  - gcc_linux-64=12.4.0=h6b7512a_5
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gxx_impl_linux-64=12.4.0=h613a52c_1
  - gxx_linux-64=12.4.0=h8489865_5
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_h5888daf_1
  - libarrow=17.0.0=hdb9dd6d_23_cpu
  - libarrow-acero=17.0.0=h5888daf_23_cpu
  - libarrow-dataset=17.0.0=h5888daf_23_cpu
  - libarrow-substrait=17.0.0=he882d9a_23_cpu
  - libblas=3.9.0=25_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=25_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-devel_linux-64=12.4.0=ha4f9413_101
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libgoogle-cloud=2.30.0=h438788a_0
  - libgoogle-cloud-storage=2.30.0=h0121fbd_0
  - libgrpc=1.65.5=hf5c653b_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libparquet=17.0.0=h6bd9018_23_cpu
  - libpng=1.6.44=hadc24fc_0
  - libprotobuf=5.27.5=h5b01275_2
  - libre2-11=2024.07.02=hbbce691_1
  - libsanitizer=12.4.0=h46f95d5_1
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=12.4.0=ha4f9413_101
  - libstdcxx-ng=14.1.0=h4852527_1
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=he137b08_1
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py311h9c9ff8c_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py311h2cbdf9a_1
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - more-itertools=10.5.0=pyhd8ed1ab_0
  - msgpack-python=1.1.0=py311hd18a35c_0
  - ncurses=6.5=he02047a_1
  - numba=0.60.0=py311h4bc866e_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - orc=2.0.2=h690cf93_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py311h7db5c69_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pillow=11.0.0=py311h49e9ac3_0
  - pip=24.2=pyh8b19718_1
  - psutil=6.0.0=py311h9ecbd09_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=17.0.0=py311hbd00459_1
  - pyarrow-core=17.0.0=py311h4510849_1_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pynisher=1.0.10=pyhd8ed1ab_0
  - pynvml=11.4.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyrfr=0.9.0=py311hd18a35c_2
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.10=hc5c86c4_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.2=py311h9ecbd09_1
  - rapids-dask-dependency=24.10.00=py_0
  - re2=2024.07.02=h77b4e00_1
  - readline=8.2=h8228510_1
  - regex=2024.9.11=py311h9ecbd09_0
  - s2n=1.5.5=h3931f03_0
  - scikit-learn=1.5.2=py311h57cc02b_1
  - scipy=1.14.1=py311he9a78e4_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - swig=4.3.0=heed6a68_0
  - sysroot_linux-64=2.17=h4a8ded7_17
  - tblib=3.0.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py311h9ecbd09_1
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alembic==1.14.0
      - annotated-types==0.7.0
      - anyio==4.7.0
      - attrs==24.3.0
      - billiard==4.2.1
      - certifi==2024.12.14
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - cmake==3.31.2
      - colorama==0.4.6
      - colorlog==6.9.0
      - configspace==1.2.1
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==3.2.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.0
      - evaluate==0.4.3
      - fastapi==0.115.6
      - filelock==3.16.1
      - flash-attn==2.5.8
      - fonttools==4.55.3
      - fraction==2.2.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.27.0
      - idna==3.10
      - interegular==0.3.3
      - jiter==0.8.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lm-eval==0.4.7
      - lm-format-enforcer==0.10.1
      - loguru==0.7.3
      - lxml==5.3.0
      - mako==1.3.8
      - matplotlib==3.10.0
      - mbstrdecoder==1.1.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numexpr==2.10.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.58.1
      - optuna==4.1.0
      - outlines==0.0.46
      - pathvalidate==3.2.1
      - peft==0.14.0
      - portalocker==3.0.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.0
      - propcache==0.2.1
      - protobuf==5.29.2
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pytablewriter==1.2.0
      - python-dotenv==1.0.1
      - pyzmq==26.2.0
      - ray==2.40.0
      - referencing==0.35.1
      - requests==2.32.3
      - rouge-score==0.1.2
      - rpds-py==0.22.3
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - sentencepiece==0.2.0
      - smac==2.2.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.36
      - sqlitedict==2.1.0
      - starlette==0.41.3
      - sympy==1.13.1
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - torch==2.3.0
      - torchvision==0.18.0
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.45.2
      - triton==2.3.0
      - typepy==1.3.4
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - vllm==0.5.1
      - vllm-flash-attn==2.5.9
      - vllm-nccl-cu12==2.18.1.0.4.0
      - watchfiles==1.0.3
      - websockets==14.1
      - word2number==1.1
      - xformers==0.0.26.post1
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: 
